name: tumorseg
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pillow
  - pip
  - matplotlib
  - torchaudio
  - torchvision
  - pytorch
  - tqdm
  - sympy
  - requests
  - jinja2
  - networkx
  - cffi
  - mpmath
  - gmpy2
  - ca-certificates
  - certifi
  - openssl
  - m2-gettext
  - zlib
  - xz
  - zstd
  - libpng
  - libjpeg-turbo
  - libtiff
  - libxml2
  - tk
  - sqlite
  - lz4-c
  - libwebp
  - libwebp-base
  - libdeflate
  - pip:
      - pygame==2.6.1
